web:
  extends:
   file: common.yml
   service: app
  command: honcho start --procfile Procfile.gunicorn
  links:
   - redis
   - postgres
web_beat:
  extends:
   file: common.yml
   service: app
  command: honcho start --procfile Procfile.gunicorn.beat
  links:
   - redis
   - postgres
redis:
  image: redis
postgres:
  build: ./docker_file/postgres
judge:
  image: registry.sdutacm.org/oj_judge
  command: nohup python protect.py &
  volumes:
   - ../oj_judge:/oj_judge
   - /data:/data
  links:
   - postgres
haproxy:
  image: tutum/haproxy
  links:
   - web
   - web_beat
  ports:
   - "80:80"
  environment:
   - BACKEND_PORT=5000
