web:
  extends:
   file: common.yml
   service: app
  links:
   - redis
   - postgres
  environment:
   OJ_SERVER_NAME: "lo.zrq495.com:5000"
web_beat:
  extends:
   file: common.yml
   service: app
  command: honcho start --procfile Procfile.beat
  links:
   - redis
   - postgres
  environment:
   OJ_SERVER_NAME: "lo.zrq495.com:5000"
redis:
  image: redis
postgres:
  build: ./docker_file/postgres
judge:
  image: registry.sdutacm.org/oj_judge
  command: nohup python protect.py &
  volumes:
   - ../oj_judge:/oj_judge
   - /data:/data
  links:
   - postgres
haproxy:
  image: tutum/haproxy
  links:
   - web
  ports:
   - "5000:80"
  environment:
   - BACKEND_PORT=5000
