web:
  build: .
  command: python manage.py runserver
  ports:
   - "5000:5000"
  volumes:
   - .:/OnlineJudge
  links:
   - redis
   - postgres
redis:
  image: redis
postgres:
  build: ./docker_file/postgres
